### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by PythonCHB** [python-packaging-tutorial/python-packaging-tutorial#2]
I see an Apache License in here now.

I'm OK with pretty much an Open Source License, but if I had a choice, I'd prefer the Creative Commons Share Alike License:

https://creativecommons.org/licenses/by-sa/3.0/us/

Others' thoughts?

**Comment by jcfr** [comment]
I suggest to have:

* Apache for code
* CC BY-SA for media, text, etc 

Source: https://opensource.stackexchange.com/questions/4400/choosing-a-license-for-a-tutorial-site

**Comment by PythonCHB** [comment]
Sounds good to me.

**Comment by PythonCHB** [comment]
I've updated the License file.
