### ISSUE TITLE
Transition to readthedocs

### ISSUE THREAD

**Issue by jcfr** [python-packaging-tutorial/python-packaging-tutorial#38]

**Comment by ChrisBarker-NOAA** [comment]
Do you want to move to the read teh docs style? or publish on readthedocs? 

Either way is fine with me, if someone wants to set it up.

-CHB

**Comment by jcfr** [comment]
All set.

The style remains unchanged but website is now automatically updated

To streamline the deployment, the associated website is now generated on readthedocs:

   https://python-packaging-tutorial.readthedocs.io

* [x] Create readthedocs project
* [x] setup webhook for automatic update
* [ ] To avoid confusion, I will shortly update the website published from the "gh-page" to redirect to the readthedocs one.
* [ ] collect readthedocs username of all @python-packaging-tutorial/contributors and associate with the readthedocs project

**Comment by ChrisBarker-NOAA** [comment]
I just changed the link in the README and the main repo page.

**Comment by jcfr** [comment]
Et voila.

Redirect to readthedocs website was done leveraging jekyll

References:
* https://help.github.com/articles/redirects-on-github-pages/
* https://github.com/jekyll/jekyll-redirect-from#redirect-to
